import "./globals.css";
import { Roboto } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import Client from "./api/client";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "CMS WP APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ApolloProvider client={Client}>
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
    // </ApolloProvider>
  );
}
